### ISSUE TITLE
writing dict to bibtex

### ISSUE THREAD

**Issue by rudrab** [sciunto-org/python-bibtexparser#413] opened 2023-10-20 16:08 UTC
This is not an "Issue". I am humbly looking for some help with bibtexparser-v2.

I am trying to convert the dict generated from other part to bibtex as:
```
  def parsing_write(self, filename):
    datalist = []
    for ref in self.TreeView.full_list:
      datadict = dict(
          (k, v) for k, v in zip(self.entries, ref) if v is not None)
      datalist.append(datadict)
    #  print(datalist)
    print(datalist)
    bibstr = bibtexparser.write_string(datalist)
    print(bibstr)
```
Where a sample `datalist` looks like:

`[{'ENTRYTYPE': 'article', 'ID': 'Wirth_1997', 'author': 'S. Wirth and A. Leithe-Jasper and A.N. Vasil{\\textquotesingle}ev and J.M.D. Coey', 'year': '1997', 'journal': 'Journal of Magnetism and Magnetic Materials', 'title': 'Structural and magnetic properties of Ni2MnGa', 'publisher': 'Elsevier {BV}', 'month': 'mar', 'number': '1-2', 'pages': 'L7--L11', 'url': 'https://doi.org/10.1016%2Fs0304-8853%2896%2900745-7', 'doi': '10.1016/s0304-8853(96)00745-7', 'volume': '167'}]`

If I run the above code, I get error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/Mkbib/main.py", line 304, in file_save_as_clicked
    self.Parser.parsing_write(filename)
  File "/usr/local/lib/python3.11/site-packages/Mkbib/pybib.py", line 55, in parsing_write
    bibstr = bibtexparser.write_string(datalist)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rudra/.local/lib/python3.12/site-packages/bibtexparser/entrypoint.py", line 168, in write_string
    library = middleware.transform(library=library)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rudra/.local/lib/python3.12/site-packages/bibtexparser/middlewares/middleware.py", line 78, in transform
    for b in library.blocks:
             ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'blocks'
```

In v1, I had:
```
    datalist = []
    writer = BibTexWriter()
    writer.indent = '    '
    for ref in self.TreeView.full_list:
      # print(type(ref))
      datadict = dict(
          (k, v) for k, v in zip(self.entries, ref) if v is not None)
      datalist.append(datadict)
    self.db.entries = datalist
    with open(filename, 'w') as bibfile:
      bibfile.write(writer.write(self.db))
```

Which used to work well, but I have I need to figure out how to make it work with v2.

**Comment by MiWeiss** [comment] 2023-10-20 20:08
Hi

Thanks for tackling the migration and trying out `v2`. Early adopters such as yourself are very helpful!

Your problem is caused by the following: `v2` does not use dicts as a representation of bibtex entries anymore, but a dedicated class.

Try to replace your datadict creation with something like the following:

```python

from bibtexparser.model import  Entry, Field

Entry(
        start_line=5,
        entry_type="article",
        raw="",
        key="someKey",
        fields=[ Field(k, v) for  k, v in zip(self.entries, ref) if k not in ["ENTRYTYPE", "ID"] and v is not None] 
 )

```

given such a list of entries, you can create a db and write the file

```python
from bibtexparser import Library

library = Library(entries)
bibtexparser.write_file(filename, library)
```

I haven't actually tested these snippets above, there's likely to be some typos in them - but they should hopefully get you back on track.

I am closing the issue, put please feel free to follow up if you have any further questions.

**Closed by MiWeiss** 2023-10-20 20:08 UTC
Labels: question

**Comment by rudrab** [comment] 2023-10-22 18:00
Dear MiWeiss,
Thanks for your help.
I have made a tiny step as:
```
def parsing_write(self, filename):
    from bibtexparser.model import Entry, Field

    print("Writing Treeview")
    print(self.TreeView.full_list)
    for ref in self.TreeView.full_list:
      datadict = Entry(entry_type=ref[0],
                       key=ref[1],
                       fields=[
                           Field(k, v)
                           for k, v in zip(self.entries[2:], ref[2:])
                           if v is not None
                       ])
      print(datadict)
    lib = bibtexparser.Library(datadict)
    bibtexparser.write_file(filename, lib)
```

But, this is only writing the last entry. I mean, the output of the following code is:
```
Writing Treeview
[('article', 'Wirth_1997', 'S. Wirth and A. Leithe-Jasper and A.N. Vasil{\\textquotesingle}ev and J.M.D. Coey', '1997', 'Journal of Magnetism and Magnetic Materials', 'Structural and magnetic properties of Ni2MnGa', 'Elsevier {BV}', None, None, None, None, None, None, None, None, None, None, 'mar', None, '1-2', None, 'L7--L11', None, None, None, 'https://doi.org/10.1016%2Fs0304-8853%2896%2900745-7', '10.1016/s0304-8853(96)00745-7', None, '167', None), ('article', 'Zaspel_2017', 'C.E. Zaspel', '2017', 'Journal of Magnetism and Magnetic Materials', 'Vortex precession in thin elliptical ferromagnetic nanodisks', 'Elsevier {BV}', None, None, None, None, None, None, None, None, None, None, 'jul', None, None, None, '59--63', None, None, None, 'https://doi.org/10.1016%2Fj.jmmm.2017.02.044', '10.1016/j.jmmm.2017.02.044', None, '433', None)]
Entry (line: None, type: `article`, key: `Wirth_1997`):
	`author` = `S. Wirth and A. Leithe-Jasper and A.N. Vasil{\textquotesingle}ev and J.M.D. Coey`
	`year` = `1997`
	`journal` = `Journal of Magnetism and Magnetic Materials`
	`title` = `Structural and magnetic properties of Ni2MnGa`
	`publisher` = `Elsevier {BV}`
	`month` = `mar`
	`number` = `1-2`
	`pages` = `L7--L11`
	`url` = `https://doi.org/10.1016%2Fs0304-8853%2896%2900745-7`
	`doi` = `10.1016/s0304-8853(96)00745-7`
	`volume` = `167`
Entry (line: None, type: `article`, key: `Zaspel_2017`):
	`author` = `C.E. Zaspel`
	`year` = `2017`
	`journal` = `Journal of Magnetism and Magnetic Materials`
	`title` = `Vortex precession in thin elliptical ferromagnetic nanodisks`
	`publisher` = `Elsevier {BV}`
	`month` = `jul`
	`pages` = `59--63`
	`url` = `https://doi.org/10.1016%2Fj.jmmm.2017.02.044`
	`doi` = `10.1016/j.jmmm.2017.02.044`
	`volume` = `433`
```
And the file `foo.bib` writes only the last entry (with the key Zaspel_2017. The first entry is lost.)
Any idea?

**Comment by MiWeiss** [comment] 2023-10-22 19:37
Sure, there's a mistake in your snipped. It's not directly related to this library, though: In the loop, you forget collecting the new entries in a list. As such, each created entry instance (except the last one) is immediately lost in the next loop iteration. Try the following:

```python
def parsing_write(self, filename):
    from bibtexparser.model import Entry, Field

    print("Writing Treeview")
    print(self.TreeView.full_list)
    entries = []
    for ref in self.TreeView.full_list:
      entry = Entry(entry_type=ref[0],
                       key=ref[1],
                       fields=[
                           Field(k, v)
                           for k, v in zip(self.entries[2:], ref[2:])
                           if v is not None
                       ])
      entries.append(entry)
    lib = bibtexparser.Library(entries)
    bibtexparser.write_file(filename, lib)
```
