### ISSUE TITLE
Edit field

### ISSUE THREAD

**Issue by tdegeus** [sciunto-org/python-bibtexparser#437] opened 2024-01-18 13:37 UTC
**Is your feature request related to a problem? Please describe.**
I would like to do some manual editing to some fields. In particular I would like to change existing fields and add extra fields. 

**Describe the solution you'd like**
The following would be a nice API
```python
bibtex_str = """
@ARTICLE{Cesar2013,
  author = {Jean César},
  title = {An amazing title},
  year = {2013},
  volume = {12},
  pages = {12--23},
  journal = {Nice Journal}
}
"""

import bibtexparser
library = bibtexparser.parse_string(bibtex_str)
library.entries[0]["title"] = "foo"
library.entries[0]["doi"] = "12345"
print(bibtexparser.write_string(library))
```
to print
```bib
@ARTICLE{Cesar2013,
  author = {Jean César},
  title = {foo},
  year = {2013},
  volume = {12},
  pages = {12--23},
  journal = {Nice Journal},
  doi = {12345}
}
```

**Use cases**
It could help automatic formatting. For example, if you have an arxiv-id `2023:1234` and you want the title to be `arXiv preprint: 2023:1234`. 

**Describe alternatives you've considered**
-

**Remaining Questions (Optional)**
Please tick all that apply:

- [x] I would be willing to to contribute a PR to fix this issue.
- [x] This issue is a blocker, I'd be greatful for an early fix.

**Comment by tdegeus** [comment] 2024-01-18 13:45
Adding a field appears also discussed in https://github.com/sciunto-org/python-bibtexparser/issues/431 and https://github.com/sciunto-org/python-bibtexparser/issues/432 . I don't know if that covers editing the field

**Comment by MiWeiss** [comment] 2024-01-18 19:38
Thanks for reporting. Indeed, this was a duplicate of #432. It's fixed now, but not yet released.

**Closed by MiWeiss** 2024-01-18 19:38 UTC
