### ISSUE TITLE
String names should not be braced

### ISSUE THREAD

**Issue by auxym** [sciunto-org/python-bibtexparser#44] opened 2014-09-25 18:41 UTC
Ref: [Tame the Beast](http://tug.ctan.org/tex-archive/info/bibtex/tamethebeast/ttb_en.pdf), p.21

```
@string{AW = "Addison-Wesley"}

@book{companion,
    author = "Goossens, Michel and Mittelbach, Franck and Samarin, Alexander",
    title = "The {{\LaTeX}} {C}ompanion",
    booktitle = "The {{\LaTeX}} {C}ompanion",
    publisher = AW,
    year = 1993,
    month = "December",
    ISBN = "0-201-54199-8",
    library = "Yes",
}
```

Writing this entry via `BibTexWriter.write` would output `publisher = {AW},`, with the string name `AW` in braces, causing bibtex to not recognize it. The correct writing has no braces.

**Comment by omangin** [comment] 2016-01-13 23:05
This is part of the discussion for #98.

**Comment by sciunto** [comment] 2016-04-09 14:45
I'm closing this as a duplicate of #98

**Closed by sciunto** 2016-04-09 14:45 UTC
