### ISSUE TITLE
Accent not parsed correctly

### ISSUE THREAD

**Issue by jvgomez** [sciunto-org/python-bibtexparser#61] opened 2015-03-19 19:20 UTC
I am a beginner in Python trying to use BibtexParser, and when I run the code on [this tutorial](https://bibtexparser.readthedocs.org/en/latest/tutorial.html#preparing-a-bibtex-file) the ouput I get, using [this code](https://gist.github.com/jvgomez/8abba1c51ea9d0c4e71a) is:

    [{u'keyword': u'keyword1, keyword2', u'title': u'An amazing title', 'ENTRYTYPE': u'article', u'journal': u'Nice Journal', u'author': u'Jean C\xe9sar', u'abstract': u'This is an abstract. This line should be long enough to test\nmultilines...', u'month': u'jan', u'volume': u'12', u'comments': u'A comment', u'year': u'2013', 'ID': 'Cesar2013', u'pages': u'12--23'}]

That is, the `é` is not properly parsed. I have tried customizations and still the same. Any help is appreciated.

**Comment by sciunto** [comment] 2016-01-12 01:03
I cannot reproduce with master. There is another (unrelated issue) with month = jan,. For now, it should be month = {jan}. See #98

I'm closing. Feel free to reopen with more details if master is not satisfying you.

**Closed by sciunto** 2016-01-12 01:03 UTC
