### ISSUE TITLE
Please document modifications of entries that are made implicitly by the parser

### ISSUE THREAD

**Issue by podkop** [sciunto-org/python-bibtexparser#390] opened 2023-08-14 15:01 UTC
This is a very useful library for me. I maintain a scientific bibliography for years in one .bib file using [JabRef](https://github.com/JabRef/jabref). Due to gradual changes in styles and formats, quite a few incompatibilities have been accumulated in the file. The library allows me to automate standardization of the bibliography.

I have just started using the library (version 1.4.0) and noticed a non-documented modification done by the parser. All the entries missing _citationkey_ are replaced with comments: `@comment{<original_entry_text>}`. I'd like to know about all possible modifications done by default, because this .bib file is "all I have", and I'd like to avoid deteriorating its quality.

Example of a top-level doc string: "Due to the fact that the field _citationkey_ is used as entry ID in the internal representation, each entry without _citationkey_ is replaced by the comment consisting of the original entry text."

_**Overall**_: is it possible to define requirements to the bibtex file guaranteeing that the contents will not be modified when parsing and exporting? Is it possible to describe all modifications to the file when the requirements are not satisfied?

Ideally, I'd like the parser to be less sensitive to the contents of the file. I've got some unfinished entries in my bibliography, because sometimes I make a quick note of a research paper with the intention to complete it later (e.g., when I can download the paper behind a paywall).

**Comment by MiWeiss** [comment] 2023-08-14 15:28
Thanks for opening the Issue. Would you mind sharing the version you are using?

**Comment by podkop** [comment] 2023-08-15 10:11
Version 1.4.0 (just added to the issue).

If this issue is relevant, I can try to update documentation. Frankly I tried to find the place in the code where an item without a citation key is wrapped into a comment, but I'm not so good programmer. If you help me to understand the logic, maybe I'll be able to document, or even refactor the code in order to avoid such modifications. Is it related to _implicit_comment_?

In my understanding, you don't need citationkey as a unique ID, since the library handles items with duplicate citationkeys. Ideally, I'd like to see a superclass that parses and exports any text like
`
@item_type_str{ key_str, key1_str = {value1_str},  key2_str = {value2_str}, ... }
`
- `item_type_str`, `key_str`, `key1_str`, `key2_str`, ... are any strings with minimum sets of forbidden characters; 
- `value1_str`, `value2_str`, ... are strings with no requirements except that the number of closing "}" is not greater than the number of opening "{";
-  `key_str` may be empty.

All the methods that handle BibTeX- or Biber-specific checks and transformations would be built on top of that. In that case, modifications of the file occur only if they are explicitly called for.

**Comment by MiWeiss** [comment] 2023-08-16 07:55
Hi @podkop 

Thanks for your reply. I will answer piece by piece:

> Version 1.4.0 (just added to the issue).

Would you mind trying out your usecase with `v2` (see the [README.md](https://github.com/sciunto-org/python-bibtexparser/blob/main/README.md)) of this repository? Much of the problematics around invalid entries are improved there, thus you may find better support for your usecase there.

> If you help me to understand the logic, maybe I'll be able to document, or even refactor the code in order to avoid such modifications. Is it related to implicit_comment?

In short: `v1` is implemented through pattern matching. Without a key, the entry does not match a known block pattern. I have not tried it, but the fact that that it is reported as an implicit comment (i.e., anything outside a valid block) seems logical. 

The silent (and often unexpected) handling of invalid blocks is a known issue in `v1` and one of the reasons we're transitioning towards `v2`, which offers a completely changed API.

> Frankly I tried to find the place in the code

Make sure you check out the `v1` branch.

> Ideally, I'd like to see a superclass that parses and exports

To avoid introducing new technical depth and regressions, we are not accepting major changes on the `v1` branch (which is very old, but still used by a very large number of repos). 
For what regards `v2`, I hope you find that your use-case is better supported. There, each block provides access to the raw bibtex; and we attempt to capture blocks for which parsing failed as `ParsingFailedBlocks`, allowing a customized handling of these blocks for arbitrary use-cases.

**Comment by podkop** [comment] 2023-08-16 10:34
Thank you very much for clarification, I'll check v2.

**Comment by MiWeiss** [comment] 2023-08-16 15:33
I am closing this for now. Please feel free to continue the conversation (and Tag me) if there's anything else

**Closed by MiWeiss** 2023-08-16 15:33 UTC
Labels: enhancement, v1
