### ISSUE TITLE
Suppress warnings

### ISSUE THREAD

**Issue by nschloe** [sciunto-org/python-bibtexparser#448] opened 2024-01-22 18:08 UTC
When parsing libraries with duplicate keys, one gets warnings, e.g.:

```python
import bibtexparser

bibfile = r"""
@article{foobar,
    author = {J. Doe},
    note = {Note 1},
    note = {Note 2},
}
"""
library = bibtexparser.parse_string(bibfile)
```
```
WARNING:root:Unknown block type <class 'bibtexparser.model.DuplicateFieldKeyBlock'>
```

Any way to suppress those?

**Comment by MiWeiss** [comment] 2024-01-22 19:51
Hey

As of now: no - there is no such option. 

I'll have to think about how to add that

**Comment by nschloe** [comment] 2024-01-23 07:30
`logging` warnings are ususally suppressed like [this](https://stackoverflow.com/a/11029841/353337), but I couldn't get it to work.

`warnings` warnings are suppressed like [this](https://stackoverflow.com/a/14463362/353337), but not sure if this is what bibtexparser uses.

**Comment by MiWeiss** [comment] 2024-01-25 20:28
> `logging` warnings are ususally suppressed like [this](https://stackoverflow.com/a/11029841/353337), but I couldn't get it to work.
> 
> `warnings` warnings are suppressed like [this](https://stackoverflow.com/a/14463362/353337), but not sure if this is what bibtexparser uses.

Yeah, the problem is that currently, we're still using the root logger, thus this approach is not going to work afaik. 

Feel free to open a PR with a nicer logging setup. That would be much appreciated.

As this question is answered, and not going into the backlog, I am closing the issue. To discuss specifics of a potential PR towards your goal, please open a dedicated isse.

**Closed by MiWeiss** 2024-01-25 20:28 UTC
Labels: enhancement
