### ISSUE TITLE
Unable to parse empty @STRING

### ISSUE THREAD

**Issue by kmccurley** [sciunto-org/python-bibtexparser#366] opened 2023-05-02 00:12 UTC
I am attempting to use the [cryptobib](https://cryptobib.di.ens.fr/) database, which contains many strings like
```
@string{acisp22ed =  ""}
```
This is completely legitimate BibTeX and defines the string acisp22ed to be empty. Unfortunately bibtexparser fails on this. The error looks like:
```
bparser.py", line 216, in <lambda>
    t['StringValue'])
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 598, in __getitem__
    return self.__tokdict[i][-1][0]
KeyError: 'StringValue'
```
Apparently StringValue cannot be empty?

**Comment by MiWeiss** [comment] 2023-05-02 05:43
Thanks for reporting.  This looks like a duplicate of #275.

**Closed by MiWeiss** 2023-05-02 05:43 UTC
