### ISSUE TITLE
Adding a field to an existing library

### ISSUE THREAD

**Issue by blucap** [sciunto-org/python-bibtexparser#431] opened 2024-01-12 23:52 UTC
Compared to the 1.4 version, relying on the documentation, the latest version makes it harder to add a new field and write the results to a file.

I wrote the below script to add DOI fields to an existing bib file. However, when converting to version 2, I noticed that adding a filed to an entry is not that easy.  I tried  `entry['doi'] = doi` and

    doi_field = Field('doi', doi)
    entry.set_field(doi_field)

and other variations, but alas, that did not work.

You may want to offer some examples of how to accomplish adding a new field.

Thanks

    import bibtexparser
    from bibtexparser.bwriter import BibTexWriter
    import requests
   
    #%%
    def find_doi(title, authors, journal, year):
        # Function to search for DOI using CrossRef API
        # Modify the search query based on available data
        query = f'{title} {authors} {journal} {year}'
        url = f'https://api.crossref.org/works?query={query}'
        response = requests.get(url)
        if response.status_code == 200:
            results = response.json()['message']['items']
            # Assumption: the first result is the correct one
            if results:
                return results[0].get('DOI', 'DOI not found')
        return 'DOI not found'
    
    def add_doi_to_bib(file_path):
        # file_path = 'bibfile.bib'
        with open(file_path) as bibtex_file:
            bib_database = bibtexparser.load(bibtex_file)
    
        for entry in bib_database.entries:
            id = entry.get('ID', '')
            title = entry.get('title', '')
            authors = entry.get('author', '')
            year = entry.get('year', '')
            journal = entry.get('journal', '')
            print(title, authors, journal, year)
            doi = find_doi(title, authors, journal, year)
            entry['doi'] = doi
    
        return bib_database
    
    def write_out(newbiblib, fo):
        writer = BibTexWriter()
        writer.contents = ['entries']
        writer.indent = '\t'
        writer.order_entries_by = ('author', 'year')
        bibtex_str = bibtexparser.dumps(newbiblib, writer)
    
        with open(fo, 'w') as fo:
            fo.write(bibtex_str)
    
    #%%
    newbiblib = add_doi_to_bib('bibfile.bib')
    
    write_out(newbiblib, "my_new_bib_file.bib")

**Comment by MiWeiss** [comment] 2024-01-14 14:06
Hey @blucap 

Thanks for opening the issue. The following snippet is certainly the expected use:

```
doi_field = Field('doi', doi)
entry.set_field(doi_field)
```

On a very short glimpse, I could not reproduce your isse. Would you mind stating more precisely what you meant with "but alas, that did not work."?  Could it be that the entry already had a doi field before your call to `set_field` (in which case, the field would be replaced)?

In either case, I like your suggestion to add a `entry['doi'] = doi` kind of setter, and will open a corresponding issue for that.

**Comment by MiWeiss** [comment] 2024-01-18 20:57
I just added more tests for this usecase and now feel confident enough to close it. Feel free to disagree if you think it needs to be re-opened.

**Closed by MiWeiss** 2024-01-18 20:57 UTC
