### ISSUE TITLE
Entries with only one field not correctly parsed

### ISSUE THREAD

**Issue by YakBizzarro** [sciunto-org/python-bibtexparser#176] opened 2017-08-07 17:12 UTC
An entry with only one field is not correctly parsed if the field doesn't end with a comma. So

> @misc{noteName,
> note = "A note with some text"
>}

is not correctly parsed, while

> @misc{noteName,
> note = "A note with some text"**,**
>}

is working.

Tested on bibtexparser 0.6.2

**Comment by omangin** [comment] 2017-08-08 21:42
Thanks @YakBizzarro. I can't reproduce your issue because I think it has been fixed in the current branch. The (soon to come) v0.7.0 should include the fix. In the meanwhile, you can install the git version.

I'm closing the issue, but please re-open if you still experience the issue with the latest development version.

**Closed by omangin** 2017-08-08 21:42 UTC
