### ISSUE TITLE
parser converts macro references to strings

### ISSUE THREAD

**Issue by diekhans** [sciunto-org/python-bibtexparser#113] opened 2016-01-24 04:42 UTC
use of macros, such as for month;

```Month = sep,```

Are converted to strings by parser, without tracking they are a macro reference.  When formatted,
the result would be:

``` month         = {sep},```

which is incorrect.   Suggest storing in a object derived from str to indicate it's a macro and still
allow easy access.

**Comment by bluebirch** [comment] 2016-01-24 09:09
This is not entirely simple, since you must also consider cases like `month = sep # " 9" # year` and thus not only use objects for values, but arrays of objects.

**Comment by sciunto** [comment] 2016-01-24 11:12
I close this as a duplicate of #98

Thanks.

**Closed by sciunto** 2016-01-24 11:12 UTC
