### ISSUE TITLE
problem with parser.ignore_nonstandard_types=False

### ISSUE THREAD

**Issue by mingtaoli** [sciunto-org/python-bibtexparser#247] opened 2019-12-18 02:48 UTC
I have two bibtex file.  If I load these two bib files with parser.ignore_nonstandard_types=False, then the late entries will be wrong. If I don't set parser.ignore_nonstandard_types = False, everything is ok.
```
import bibtexparser

from bibtexparser.bparser import BibTexParser

parser = BibTexParser(common_strings=False)
parser.ignore_nonstandard_types = False

with open('a.bib', encoding='utf8') as filea:
    a_database = bibtexparser.load(filea, parser)

print(len(a_database.entries))

with open('b.bib', encoding='utf8') as fileb:
    b_database = bibtexparser.load(fileb, parser)
print(len(b_database.entries))
```

a.bib--------------------
```
@article{FuMetalhalideperovskite2019,
    author = {Yongping Fu and Haiming Zhu and Jie Chen and Matthew P. Hautzinger and X.-Y. Zhu and Song Jin},
    doi = {10.1038/s41578-019-0080-9},
    journal = {Nature Reviews Materials},
    month = {feb},
    number = {3},
    pages = {169-188},
    publisher = {Springer Science and Business Media {LLC}},
    title = {Metal halide perovskite nanostructures for optoelectronic applications and the study of physical properties},
    url = {https://www.nature.com/articles/s41578-019-0080-9},
    volume = {4},
    year = {2019}
}
```

b.bib--------------------
```
@article{FuMetalhalideperovskite2019,
    author = {Yongping Fu and Haiming Zhu and Jie Chen and Matthew P. Hautzinger and X.-Y. Zhu and Song Jin},
    doi = {10.1038/s41578-019-0080-9},
    journal = {Nature Reviews Materials},
    month = {feb},
    number = {3},
    pages = {169-188},
    publisher = {Springer Science and Business Media {LLC}},
    title = {Metal halide perovskite nanostructures for optoelectronic applications and the study of physical properties},
    url = {https://www.nature.com/articles/s41578-019-0080-9},
    volume = {4},
    year = {2019}
}

@article{SunEnablingSiliconSolar2014,
    author = {Ke Sun and Shaohua Shen and Yongqi Liang and Paul E. Burrows and Samuel S. Mao and Deli Wang},
    doi = {10.1021/cr300459q},
    journal = {Chemical Reviews},
    month = {aug},
    number = {17},
    pages = {8662-8719},
    publisher = {American Chemical Society ({ACS})},
    title = {Enabling Silicon for Solar-Fuel Production},
    url = {http://pubs.acs.org/doi/10.1021/cr300459q},
    volume = {114},
    year = {2014}
}

@article{LiuPhotocatalytichydrogenproduction2016,
    author = {Maochang Liu and Yubin Chen and Jinzhan Su and Jinwen Shi and Xixi Wang and Liejin Guo},
    doi = {10.1038/nenergy.2016.151},
    impactfactor = {54.000},
    journal = {Nature Energy},
    month = {sep},
    number = {11},
    pages = {16151},
    publisher = {Springer Science and Business Media {LLC}},
    title = {Photocatalytic hydrogen production using twinned nanocrystals and an unanchored {NiSx} co-catalyst},
    url = {http://www.nature.com/articles/nenergy2016151},
    volume = {1},
    year = {2016}
}
```

**Comment by MiWeiss** [comment] 2022-07-10 10:47
I can't reproduce this issue. For the files provided by you, the parsing result appears identical, independent on whether is set `parser.ignore_nonstandard_types = False`. This is expected, as all entries are `@article`. This issue is quite old, hence I assume the problem has been fixed in the meantime.

However, your snippet revealed another issue: Re-using a parser does not clear its state; hence the second parse also returns the entry of the first parse. This will be handled in a separate issue.

**Closed by MiWeiss** 2022-07-10 10:47 UTC
Labels: cannot reproduce
