### ISSUE TITLE
Errors in name-split

### ISSUE THREAD

**Issue by tdegeus** [sciunto-org/python-bibtexparser#441] opened 2024-01-18 16:46 UTC
**Describe the bug**
Error in name split.
*Note that I took this from the test of v1. I think that those test should be included in the tests of v2.*

**Reproducing**

Version: `2.0.0b5`

Code:
```python
bibtex_str = """
@ARTICLE{Cesar2013,
  author = {{Delgado de Molina}, A. and Vign{\'e}, M. and {de Geus}, Tom},
  title = {An amazing title},
  year = {2013},
  pages = {12--23},
  volume = {12},
  journal = {Nice Journal}
}
"""

import bibtexparser
import bibtexparser.middlewares as m

layers = [
    m.SeparateCoAuthors(True),
    m.SplitNameParts(True),
]
library = bibtexparser.parse_string(bibtex_str, append_middleware=layers)
print(library.entries[0]['author'])
```

Output:
```
[NameParts(first=['A.'], von=[], last=['{Delgado de Molina}'], jr=[]), NameParts(first=['Tom'], von=[], last=["Vign{'e}"], jr=['M.', 'and', '{de Geus}'])]
```
Expected output:
```
[NameParts(first=['A.'], von=[], last=['{Delgado de Molina}'], jr=[]), NameParts(first=['M.'], von=[], last=["Vign{'e}"], jr=[]), NameParts(first=['Tom'], von=[], last=["{de Geus}"], jr=[])]
```

**Workaround**
-

**Remaining Questions (Optional)**
Please tick all that apply:

- [ ] I would be willing to contribute a PR to fix this issue.
- [x] This issue is a blocker, I'd be grateful for an early fix.

**Comment by tdegeus** [comment] 2024-01-18 16:47
Equally breaking
```
author = {{Ben Arous}, {G{\'{e}}rard} and {de Geus}, Tom},
```

**Comment by MiWeiss** [comment] 2024-01-18 21:22
Thanks a lot for your report. Looks like the test cases you are referring to were merged into `v1` after the two versions forked branches. Also, migrating said PR (which was one of yours) is not going to be trivial as `v2` does not use the same underlying logic (it's not new either, there were just multiple ones in `v1` and open PRs, between which I ultimately had to choose).

This definitely needs to be looked at. Not sure if and when I find the time, thus, if anyone wants to take over, please comment and volunteer.

Some info from my reproduction:
- The error lies in the `SeparateCoAuthors` part
- The test cases to reproduce this issue can be found on the `reproduce-441` branch [here](https://github.com/sciunto-org/python-bibtexparser/compare/main...reproduce-441#diff-9790e58590860641069d6ff9474f96b1d9ecf5b4b81dde9e1380dd703532886e)

**Comment by tdegeus** [comment] 2024-01-22 14:56
Thanks. I will have a look (but probably not this week)

**Closed** 2024-02-07 19:55 UTC
Labels: bug, needs help, v2, reproduced
