### ISSUE TITLE
Parse error due to expand string

### ISSUE THREAD

**Issue by tmensink** [sciunto-org/python-bibtexparser#139] opened 2016-06-07 13:56 UTC
For some reason I get an parse error due to the expand string (in bibdatabase.py). The reason is, that self.strings is empty, and then indeed the name does not exist. 

With this little return statement:

```
  def expand_string(self, name):        
        try:
            return self.strings[name]
        except KeyError:
            return name            
            #raise(KeyError("Unknown string: {}.".format(name)))
```

The code runs for me. I'm more than happy to make it a pull request (need some explanation there, it would be the first time), albeit I cant believe this is very specific to my setup.

**Comment by Phyks** [comment] 2017-03-30 14:22
Closing as a duplicate of https://github.com/sciunto-org/python-bibtexparser/issues/98.

**Closed by Phyks** 2017-03-30 14:22 UTC
