### ISSUE TITLE
Errors in unicode conversion

### ISSUE THREAD

**Issue by rbawden** [sciunto-org/python-bibtexparser#274] opened 2021-01-09 10:42 UTC
I have come across some problems in the conversion to unicode. I have been using the following code to parse a raw bibtex string (hal_bibtex) using BibTexParser, and although some of the more common escaped characters are correctly converted, others seem to contain some errors:

```
from bibtexparser.bparser import BibTexParser
from bibtexparser.customization import convert_to_unicode

parser = BibTexParser()
parser.customization = convert_to_unicode
info = bibtexparser.loads(hal_bibtex, parser=parser)
```

For example, I tried it out on the following bibtex file : https://hal.inria.fr/hal-01682188v1/bibtex, which contains a large number of accented characters. The result contains at least the following errors:

Bibtex:
> ... Katar{\'i}na ... Gr{\=u}z{\=i}tis ... Jel{\'i}nek ... Ljube{\v s}i{\'c} ... Mart{\'i}nez Alonso ... Ne{\v s}pore-B{\=e}rzkalne ... Samard{\v z}i{\'c} ... Saul{\=i}te, ...

Once converted to unicode:
> ... Katar\ńa ... and Grūz\̄tis ... and Jel\'ék ... and Ljubeši\'cŃikola ... Mart\'in ́Alonso, ... Nešpore-B\=r̄zkalne ... Samardži\'c ... Saul\=iē, ...

Expected output:
> ... Katarína ... and Grūzītis ... and Jelínek ... and Ljubešić Nikola ... Martínez Alonso, ... Nešpore‐bērzkalne  ... Samardžić ... Saulīte, ...

Thanks in advance for your help!

**Comment by MiWeiss** [comment] 2022-07-09 09:28
Duplicate of #272. There's also a workaround provided there.

**Closed by MiWeiss** 2022-07-09 09:28 UTC
