### ISSUE TITLE
Can't load utf8

### ISSUE THREAD

**Issue by dsakurai** [sciunto-org/python-bibtexparser#136] opened 2016-05-12 06:02 UTC
I tried loading a file encoded in utf8:

``` .py
with open("test.bib") as bibtex_file:
  bibtexparser.load(bibtex_file)
```

While bibtexparser 0.6.2 has no trouble with python 2.7, python 3.5 gives me this error:

```
Traceback (most recent call last):
  File "parsebib.py", line 8, in <module>
    bibtexparser.load(bibtex_file)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bibtexparser/__init__.py", line 59, in load
    return parser.parse_file(bibtex_file)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bibtexparser/bparser.py", line 130, in parse_file
    return self.parse(file.read())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 38: ordinal not in range(128)
```

The content of `test.bib`:

``` .bib
@ARTICLE{Cesar2013,
  author = {Jean César},
  title = {An amazing title},
  year = {2013},
  month = jan,
  volume = {12},
  pages = {12--23},
  journal = {Nice Journal},
  abstract = {This is an abstract. This line should be long enough to test
     multilines...},
  comments = {A comment},
  keywords = {keyword1, keyword2}
}
```

Thanks.

**Comment by joelfrederico** [comment] 2016-07-21 22:58
Load your file with the proper encoding:

with open("test.bib", encoding='utf-8') as bibtex_file:
  bibtexparser.load(bibtex_file)

**Comment by sg-s** [comment] 2017-03-03 14:19
@dsakurai the problem is here:

```
 author = {Jean César},
```

**Comment by sciunto** [comment] 2017-03-22 18:53
I'm closing. Feel free to reopen if there is still an issue.

**Closed by sciunto** 2017-03-22 18:53 UTC
